### ISSUE TITLE
Include Search and Pagination

### ISSUE THREAD

**Issue by garkell** [ceford/j4xdemos-com-mywalks#1]
Hi Cliff,
Thanks for this example, it's really helpful.  As a training exercise for myself I am working on adding search and pagination to the example as advanced features.  Are you happy for me to do this and update the code?  Cheers.
Glenn
glennarkell@gmail.com

**Comment by ceford** [comment]
I know that my code and my tutorial are both out of date. For example, one thing I remember is that autoload_psr4.php moved from libraries to administrator/cache. Something I am concerned about is 'simple' becoming 'comprehensive'. I have seen a draft of the CMS Tutorial and it is massive - overwhelming. Do you think you could devise a new tutorial that is an extension to my tutorial? Something like 'Adding Search and Pagination ...'. That way users can absorb it in chunks.
